language: python

python:
  - "2.7"

env:
  - TOXENV=py26-1.5.X,py32-1.5.X
  - TOXENV=py26-1.6.X,py33-1.6.X
  - TOXENV=py27-1.7.X,py33-1.7.X

install:
  - pip install tox

script:
    - tox

branches:
  only:
    - master